PostHog/squeak

pages/setup/notifications.tsx
pages/setup/welcome.tsx

Remove GitHub and add company info to notifcations tab

---

pages/setup/snippet.tsx

- Updates snippet language for better formatting

Update snippet language

---

pages/login.tsx

Email and password on /login

---

components/CodeSnippet.tsx
components/ProfileTable.tsx
layout/AdminLayout.tsx
layout/ErrorLayout.tsx
layout/SetupLayout.tsx
pages/index.tsx
pages/questions.tsx
pages/settings.tsx
pages/setup/snippet.tsx
pages/users.tsx
styles/globals.css
util/withAdminAccess.ts

Basic admin layout / pages

---

pages/setup/database.tsx

Tweak message when database URL is not provided

---

components/Button.tsx
components/CodeSnippet.tsx
components/InviteUser.tsx
components/ProfileForm.tsx
components/ProfileTable.tsx
components/SignupForm.tsx
components/SlackManifestSnippet.tsx
components/WebhookTable.tsx
components/setup/SetupProfile.tsx
components/setup/SetupSignUp.tsx
layout/AdminLayout.tsx
layout/ErrorLayout.tsx
layout/LoginLayout.tsx
pages/forgot-password.tsx
pages/login.tsx
pages/questions.tsx
pages/setup/alerts.tsx
pages/setup/database.tsx
pages/setup/notifications.tsx
pages/signup/index.tsx
styles/globals.css
tailwind.config.js

replaces default tw colors with a custom color set

---

pages/api/question/resolve.ts

Add resolved bool to `/api/question/resolve` endpoint to allow questions to be marked as unresolved

Add resolved bool to endpoint

---

components/CodeSnippet.tsx

Update snippet URL to use CloudFront

---

components/ResetPassword.js
pages/reset-password.tsx

- Adds a reset password page for the snippet to redirect to after confirming their password reset email

Add a reset password page

---

components/EditQuestionModal.js
layout/AdminLayout.tsx
pages/question/[id].js
pages/questions.tsx

moving thread settings to sidebar instead of modal

---

components/question/EditQuestion.tsx
components/question/SlugModal.tsx
components/question/SlugTable.tsx
components/settings/AllowedOriginModal.tsx
pages/question/[id].js

Improves handling for multiple slugs

---

.env.example
components/SlackTableSkeleton.tsx
layout/AdminLayout.tsx
pages/api/slack/messages.ts
pages/questions.tsx
pages/slack.tsx
styles/globals.css

New UI for Slack import page

---

util/sendReplyNotification.ts

- Adds correct link to where the question was asked

Fix email notifications

---

@types/supabase.d.ts
components/Input.tsx
components/PermalinkSettings.tsx
components/Toggle.tsx
components/question/EditQuestion.tsx
migrations/1655489959884_permalinks.js
package.json
pages/api/config.ts
pages/api/question/index.ts
pages/question/[id].js
pages/settings.tsx
util/getQuestion.ts
util/getQuestions.ts
yarn.lock

- Automatically adds permalink slug to each question based on the question subject
- If permalink exists, the question ID is appended to the end
- Allows users to edit permalinks
- Adds "Enable permalinks" section to the settings page
- If enabled, adds links to individual question pages on the timestamp in squeak-react
- Adds permalink base section to settings page (if permalinks are enabled)
- Useful for users who have a root path for their question pages (/questions/question)

Permalinks

---

util/checkAllowedOrigins.ts

- Allow get requests in checkAllowedOrigins

Allow get requests in checkAllowedOrigins

---

util/formatSlackMessage.js

- Adds channel element type to formatSlackMessage.js

Add channel type

---

util/getQuestions.ts

- Select question topics in `getQuestions`
Needed to show available topics on the front end

Select question topics in getQuestions

---

pages/api/user.ts

- Adds first and last name to user response

Add first and last name to user endpoint

---

.env
components/Select.tsx
components/Topics.tsx
layout/AdminLayout.tsx
lib/api/topics.ts
pages/api/topic-groups.ts
pages/api/topics/[id].ts
pages/api/topics/create.ts
pages/api/topics/index.ts
pages/topics.tsx
prisma/migrations/20220831183424_topic_groups/migration.sql
prisma/schema.prisma

- Adds the ability to group topics

Topic groups

---

pages/topics.tsx

- Sets initial value to first topic group

Topic group initial value

---

.babelrc
.env.example
.gitignore
@types/environment.d.ts
hooks/usePostHog.ts
package.json
pages/api/user-setup.ts
pages/signup/profile.tsx
prisma/schema.prisma
util/posthog/trackUserSignup.ts
util/posthog/withPostHog.ts
yarn.lock

This patch fixes a couple of small issues that arose when tracking the signup flow. Previously, we had been doing a lot of extra identifies and aliases, which were not needed. 
This also fixes a couple of other small bugs I noticed in the signup flow.

Fix small issues with tracking

---

.github/workflows/ci-e2e.yml
.gitignore
cypress.config.ts
cypress/e2e/auth.cy.js
cypress/fixtures/example.json
cypress/helpers.ts
cypress/support/commands.ts
cypress/support/e2e.ts
cypress/support/index.d.ts
docker-compose.yml
lib/auth/cookies.ts
package.json
pages/api/logout.ts
pages/api/signup.ts
pages/login.tsx
prisma/seed.ts
tsconfig.json
util/getActiveOrganization.ts
yarn.lock

Adds some basic E2E testing for login using Cypress. More testing for other parts of the app coming soon.

Add E2E testing for login and signup

---

pages/team/[id].tsx

Add combobox to Add member

---

cypress/e2e/teams.cy.js
package.json
prisma/seed.ts

Adds some basic e2e tests for creating, updating, and deleting teams

ci: add e2e tests for teams

---

.github/workflows/ci-e2e.yml
cypress/e2e/teams.cy.js
prisma/migrations/20220930001953_team_requirement/migration.sql
prisma/schema.prisma
src/components/RoadmapTable.tsx
src/layout/AdminLayout.tsx
src/lib/api/roadmap.ts
src/pages/api/roadmap/[id].ts
src/pages/api/roadmap/index.tsx
src/pages/api/teams.ts
src/pages/roadmap.tsx

- Adds `/roadmap` page that displays _all_ goals for every team
- Allows goals to be created without assigning a team
- Allows goals to be moved between teams

Roadmap page

---

prisma/migrations/20221007012949_cascade_replies/migration.sql
prisma/schema.prisma
yarn.lock

Cascade deleting or updating of questions to all their replies.
Closes #156.

chore: cascade delete and update of questions to replies

---

prisma/migrations/20221021153347_beta_available/migration.sql
prisma/schema.prisma
src/components/RoadmapTable.tsx
src/pages/roadmap.tsx
src/pages/team/[id].tsx

- Adds "Beta available" checkbox to goals
- All categories now appear when adding a category

Add beta available toggle / fix category population

---

src/pages/api/profiles/[id].ts

- Allows admins and now users to update the following profile fields:
first_name, last_name, website, github, linkedin, twitter, biography, teamId, role

Allow editing other profile fields

---

src/util/getQuestions.ts

We are having some issues on posthog.com which appears to be a result of this change. I'll revert then fix separately.
This reverts chttps://github.com/PostHog/squeak/pull/243

revert(topics): revert change to include topics in question

---

packages/squeak/package.json
packages/squeak/prisma/migrations/20221109182422_cloudinary_config/migration.sql
packages/squeak/prisma/migrations/20221109220209_images/migration.sql
packages/squeak/prisma/schema.prisma
packages/squeak/src/components/ImageSettings.tsx
packages/squeak/src/components/ImageUpload.tsx
packages/squeak/src/components/Modal.tsx
packages/squeak/src/components/RoadmapTable.tsx
packages/squeak/src/pages/api/config.ts
packages/squeak/src/pages/api/image.ts
packages/squeak/src/pages/api/roadmap/index.tsx
packages/squeak/src/pages/api/teams.ts
packages/squeak/src/pages/roadmap.tsx
packages/squeak/src/pages/settings.tsx
packages/squeak/src/pages/team/[id].tsx
packages/squeak/src/util/cloudinary.ts
packages/squeak/src/util/formidable.js
packages/squeak/yarn.lock

- Allows attaching images to roadmap items
- Adds faux Cloudinary integration by allowing users to enter their Cloudinary credentials on `/settings`
- If Cloudinary creds are _not_ present in the org, image upload features are hidden

Add image support

---

packages/squeak/src/pages/api/teams.ts

- Allows non-logged-in users to fetch teams

Allow non-logged-in users to fetch teams

---

packages/squeak/src/pages/api/roadmap/index.tsx

- Fixes roadmap endpoint to use correct org ID

Fix roadmap endpoint

---

packages/squeak/src/util/sendReplyNotification.ts

— Removed “!” was making link feel like a NOT and something unusual 
— Made the important headlines bold
— Proper spacing added
**Before:**
**After:**

Improve Email Template

---

packages/squeak/src/components/question/EditQuestion.tsx
packages/squeak/src/db/question.ts

- Returns permalink in `getQuestion` function
- Makes editing a permalink actually work

Fix permalinks

---

packages/squeak/src/db/question.ts
packages/squeak/src/pages/api/question/index.ts

- Correctly appends the message ID to the end of a permalink if another question has the same permalink
- Adds strict rule to slugify to strip more characters in permalinks

Fix unique slugs

---

packages/squeak-react/src/components/Theme.tsx

- Adds richtext button color CSS variable
- Fixes richtext buttons not appearing in dark mode

Add richtext button color CSS variable

---

packages/squeak-react/src/components/Theme.tsx

- Changes login error text color to red

Change error text color

---

packages/squeak/prisma/migrations/20230118232116_profile_images/migration.sql
packages/squeak/prisma/schema.prisma
packages/squeak/src/pages/api/image.ts
packages/squeak/src/pages/api/profiles/[id].ts
packages/squeak/src/util/cloudinary.ts

- Allows users to update their avatar with an uploaded image
- Crops all uploaded images to 80 x 80 pixels
- Fixes image endpoint cors issue
- Assigns a user ID and date to each image uploaded

Avatar updates

---

packages/squeak/src/pages/api/profiles/[id].ts
packages/squeak/src/util/checkAllowedOrigins.ts

- Checks for organization ID in both body and query for all requests
- Ignore image update to user profiles if image data doesn't exist

Small fixes

---

packages/squeak/src/pages/api/profiles/leaderboard.tsx

- Orders leaderboard by reply count

Order leaderboard by reply count

---

packages/squeak/src/pages/api/profiles/leaderboard.tsx

- Ignores admins on leaderboard endpoint

Disregard admins in leaderboard

---

packages/squeak/src/pages/api/question/index.ts
packages/squeak/src/util/sendQuestionAlert.ts

Adds a few fields to webhooks:
- html (parsed markdown question body)
- user (full name, email)
- permalink (question permalink)
- id (the question id)

Better webhooks
